### ISSUE TITLE
Missing README content

### ISSUE THREAD

**Issue by benblayer** [nmaoez/composer-language-server#2]
Hi,

Can you please further explain how does the grammar defined in the LSP project reflected in the Monaco Editor?
Because it seems that it only cares about the "language-mode.js" file rather than the Expression.xtext file.

Thanks.

**Comment by nmaoez** [comment]
Hi!

The `language-mode.js`-file is the Monarch language definition for syntax highlighting and with the invocation of the function `setMonarchTokensProvider()` we define that for a specific language id this Monarch language definition should be responsible. See the Monaco Editor API docs for more information [here](https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#setmonarchtokensprovider).

The language definition with Xtext will reflect in e.g. the error highlighting or auto completion within the editor. You can see the messages sent between the sockets in the network tab in your browsers developer tools.
Also have a look at the org.eclipse.xtext.ide.server.LanguageServerImpl class. There you can see which notifications are provided by the language server from Xtext (see the language server specification for all available notifications [here](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_didOpen)).

Cheers.

**Comment by benblayer** [comment]
Thanks for the quick response.
I just noticed there's some issue with the language server deployment.
after it prints "start", it throws the error:
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.IllegalStateException: This language server has already been initialized.
	at org.eclipse.xtext.ide.server.LanguageServerImpl.initialize(LanguageServerImpl.java:236)
	... 16 more


Are you familiar with this?

Thanks

**Comment by nmaoez** [comment]
```
Caused by: java.lang.IllegalStateException: This language server has already been initialized.
at org.eclipse.xtext.ide.server.LanguageServerImpl.initialize(LanguageServerImpl.java:236)
```
I think you already have the language server somewhere running. Reboot you pc or kill the corresponding process and it will be running again.

**Comment by benblayer** [comment]
I'll try to be more specific...
I did the following steps:
1) Changed the 'Hello' string in Expression.xtext to: 'Goodbye'.
2) Run 'GenerateExpression.mwe2' as MWE2 workflow.
3) In root folder run: ./gradlew clean build.
4) Run the server (RunWebserverSocket3)
5) Console printed: 'start'.
6) In monaco-editor-lsp-example run: npm run serv.
7) On the browser: typing 'Goodbye' on a new line in the editor.

I expected to see some behaviour (completion, colouring etc) but none shown.

**Comment by benblayer** [comment]
Is there any support for some of the common features (completion, coloring etc)? And where is it located?

**Comment by nmaoez** [comment]
With the exact steps you described I could changed the autocompletion from 'Hello' to 'Goodbye'. Did you really closed the old language server, build it new and run it?

Unfortunatly there isn't a good documentation for the [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient). We as a team had to read source code to get it a little sense of how the language server works and we still are not 100% confident.
