### ISSUE TITLE
General error during semantic analysis: Unsupported class file major version 57

### ISSUE THREAD

**Issue by chengtie** [nmaoez/composer-language-server#5]
I tried to run this project under Windows. 

While importing the project, I got the following error:

![Screenshot 2020-04-05 at 08 24 36](https://user-images.githubusercontent.com/774409/78468303-fdd80500-7716-11ea-9ca1-ecf92d845a30.png)

Then I got the following error for `.\gradlew.bat clean build`:

```
C:\Users\chengtie\eclipse-workspace\composer-language-server>.\gradlew.bat clean build

Welcome to Gradle 5.4!

Here are the highlights of this release:
 - Run builds with JDK12
 - New API for Incremental Tasks
 - Updates to native projects, including Swift 5 support

For more details see https://docs.gradle.org/5.4/release-notes.html


FAILURE: Build failed with an exception.

* Where:
Settings file 'C:\Users\chengtie\eclipse-workspace\composer-language-server\settings.gradle'

* What went wrong:
Could not compile settings file 'C:\Users\chengtie\eclipse-workspace\composer-language-server\settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 57

  java.lang.IllegalArgumentException: Unsupported class file major version 57
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:184)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:152)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:273)
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
        at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:254)
        at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:192)
        at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:172)
        at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:128)
        at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClassNullable(AsmReferenceResolver.java:59)
        at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClass(AsmReferenceResolver.java:46)
        at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveNonArrayType(AsmReferenceResolver.java:81)
        at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveType(AsmReferenceResolver.java:72)
        at org.codehaus.groovy.ast.decompiled.MemberSignatureParser.createMethodNode(MemberSignatureParser.java:55)
        at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lazyInitMembers(DecompiledClassNode.java:195)
        at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.getDeclaredMethods(DecompiledClassNode.java:121)
```

Could anyone help?

**Comment by nmaoez** [comment]
Which JDK version is installed on your machine? I guess Gradle has problems with your current JDK version. See [here](https://github.com/gradle/gradle/issues/8681). On my local machine I have the following JDK installed and the project starts as expected:

```sh
$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)
```

Also I had to update the lsp4j dependency. The master should work now.

**Comment by chengtie** [comment]
I installed `jdk1.8.0_241` now.

The error during importing the project disappeared.

But build failed:

```
$ ./gradlew clean build

Welcome to Gradle 5.4!

Here are the highlights of this release:
 - Run builds with JDK12
 - New API for Incremental Tasks
 - Updates to native projects, including Swift 5 support

For more details see https://docs.gradle.org/5.4/release-notes.html


> Task :com.novomind.language.server.expression:generateXtextLanguage
0    [main] INFO  text.xtext.generator.XtextGenerator  - Initializing Xtext generator
7    [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Adding generated EPackage 'org.eclipse.xtext.common.types.TypesPackage'
107  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project com.novomind.language.server.expression at 'file:/Users/chengtie/Startup/OCamlProjects/composer-language-server/com.novomind.language.server.expression/'
108  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project com.novomind.language.server.expression.tests at 'file:/Users/chengtie/Startup/OCamlProjects/composer-language-server/com.novomind.language.server.expression.tests/'
108  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project com.novomind.language.server.expression.ide at 'file:/Users/chengtie/Startup/OCamlProjects/composer-language-server/com.novomind.language.server.expression.ide/'
116  [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Using resourceSet registry. The registered Packages will not be registered in the global EPackage.Registry.INSTANCE!
362  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/Xtext/Xbase/XAnnotations' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
366  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/xbase/Xtype' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
383  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/xbase/Xbase' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
383  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/common/JavaVMTypes' from 'platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.genmodel'
857  [main] INFO  erator.parser.antlr.AntlrToolFacade  - Downloading file from 'http://download.itemis.com/antlr-generator-3.2.0-patch.jar' ...
17171 [main] INFO  erator.parser.antlr.AntlrToolFacade  - Finished downloading.
17183 [main] INFO  text.xtext.generator.XtextGenerator  - Generating com.novomind.language.server.Expression
17812 [main] INFO  nerator.ecore.EMFGeneratorFragment2  - Generating EMF model code
17836 [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.novomind.com/language/server/Expression' from 'platform:/resource/com.novomind.language.server.expression/model/generated/Expression.genmodel'
19119 [main] INFO  text.xtext.generator.XtextGenerator  - Generating common infrastructure
19121 [main] INFO  .emf.mwe2.runtime.workflow.Workflow  - Done.

> Task :com.novomind.language.server.expression:generateXtext
WARNING:The extension com.novomind.language.server.services.ExpressionGrammarAccess is not used in ExpressionFormatter (file:/Users/chengtie/Startup/OCamlProjects/composer-language-server/com.novomind.language.server.expression/src/com/novomind/language/server/formatting2/ExpressionFormatter.xtend line : 14 column : 
> Task :com.novomind.language.server.expression.ide:generateXtext FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':com.novomind.language.server.expression.ide:generateXtext'.
> Could not resolve all files for configuration ':com.novomind.language.server.expression.ide:compileClasspath'.
   > Could not find org.eclipse.lsp4j:org.eclipse.lsp4j:0.8.0-SNAPSHOT.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/lsp4j/org.eclipse.lsp4j/0.8.0-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/lsp4j/org.eclipse.lsp4j/0.8.0-SNAPSHOT/org.eclipse.lsp4j-0.8.0-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/lsp4j/org.eclipse.lsp4j/0.8.0-SNAPSHOT/org.eclipse.lsp4j-0.8.0-SNAPSHOT.jar
       - https://jcenter.bintray.com/org/eclipse/lsp4j/org.eclipse.lsp4j/0.8.0-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/org/eclipse/lsp4j/org.eclipse.lsp4j/0.8.0-SNAPSHOT/org.eclipse.lsp4j-0.8.0-SNAPSHOT.pom
       - https://jcenter.bintray.com/org/eclipse/lsp4j/org.eclipse.lsp4j/0.8.0-SNAPSHOT/org.eclipse.lsp4j-0.8.0-SNAPSHOT.jar
     Required by:
         project :com.novomind.language.server.expression.ide
   > Could not find org.eclipse.lsp4j:org.eclipse.lsp4j.websocket:0.8.0-SNAPSHOT.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/lsp4j/org.eclipse.lsp4j.websocket/0.8.0-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/lsp4j/org.eclipse.lsp4j.websocket/0.8.0-SNAPSHOT/org.eclipse.lsp4j.websocket-0.8.0-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/lsp4j/org.eclipse.lsp4j.websocket/0.8.0-SNAPSHOT/org.eclipse.lsp4j.websocket-0.8.0-SNAPSHOT.jar
       - https://jcenter.bintray.com/org/eclipse/lsp4j/org.eclipse.lsp4j.websocket/0.8.0-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/org/eclipse/lsp4j/org.eclipse.lsp4j.websocket/0.8.0-SNAPSHOT/org.eclipse.lsp4j.websocket-0.8.0-SNAPSHOT.pom
       - https://jcenter.bintray.com/org/eclipse/lsp4j/org.eclipse.lsp4j.websocket/0.8.0-SNAPSHOT/org.eclipse.lsp4j.websocket-0.8.0-SNAPSHOT.jar
     Required by:
         project :com.novomind.language.server.expression.ide
   > Could not find org.eclipse.lsp4j:org.eclipse.lsp4j:0.8.0-SNAPSHOT.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/lsp4j/org.eclipse.lsp4j/0.8.0-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/lsp4j/org.eclipse.lsp4j/0.8.0-SNAPSHOT/org.eclipse.lsp4j-0.8.0-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/lsp4j/org.eclipse.lsp4j/0.8.0-SNAPSHOT/org.eclipse.lsp4j-0.8.0-SNAPSHOT.jar
       - https://jcenter.bintray.com/org/eclipse/lsp4j/org.eclipse.lsp4j/0.8.0-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/org/eclipse/lsp4j/org.eclipse.lsp4j/0.8.0-SNAPSHOT/org.eclipse.lsp4j-0.8.0-SNAPSHOT.pom
       - https://jcenter.bintray.com/org/eclipse/lsp4j/org.eclipse.lsp4j/0.8.0-SNAPSHOT/org.eclipse.lsp4j-0.8.0-SNAPSHOT.jar
     Required by:
         project :com.novomind.language.server.expression.ide > org.eclipse.xtext:xtext-dev-bom:2.18.0
         project :com.novomind.language.server.expression.ide > org.eclipse.xtext:org.eclipse.xtext.ide:2.18.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 28s
11 actionable tasks: 6 executed, 5 up-to-date
```

Does anyone have any idea?

**Comment by nmaoez** [comment]
I also had this error, since the dependency `org.eclipse.lsp4j:org.eclipse.lsp4j:0.8.0-SNAPSHOT` does not exist anymore. I pushed some changes to the master branch. Please update your local project or clone the project again.

**Comment by chengtie** [comment]
OK, after pulling from the master branch, `./gradlew clean build` worked.

But for `npm run serv` in `monaco-editor-lsp-example`. After `sudo npm install -g --force nodemon`, `npm install webpack-dev-server -g`,  and `npm link webpack`, it returned an error:

```
$ npm run serv

> monaco-editor-lsp-example@0.0.1 serv /Users/chengtie/Startup/OCamlProjects/composer-language-server/monaco-editor-lsp-example
> nodemon --watch webpack.config.js --exec "webpack-dev-server --mode development --open"

[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): webpack.config.js
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `webpack-dev-server --mode development --open`
The CLI moved into a separate package: webpack-cli
Please install 'webpack-cli' in addition to webpack itself to use the CLI
-> When using npm: npm i -D webpack-cli
-> When using yarn: yarn add -D webpack-cli
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- /usr/local/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by nmaoez** [comment]
The error states that you have to install 'webpack-cli' in addition to webpack yourself to use the CLI. Maybe thats the problem? So you have to execute this command additionally?
```sh
npm i -D webpack-cli
```

**Comment by chengtie** [comment]
I did `npm install` again, `npm run serv` worked.

Here is the new error. `ws://localhost:4389/` returned errors:

![Screenshot 2020-04-06 at 17 09 49](https://user-images.githubusercontent.com/774409/78573929-96f74080-7829-11ea-9a0b-cf86b6fadd23.png)

**Comment by nmaoez** [comment]
Please check if the application is already running on your machine. If the needed port is already blocked, a new one is selected and therefore the frontend tries to connect to the wrong port. I had to restart my machine since I could find the corresponding processes.

**Comment by chengtie** [comment]
I redid `npm install` under `monaco-editor-lsp-example`, it helped.

The process for testing I follow is 1) run `./gradlew run` in terminal; 2) open `http://localhost:8080` in Chrome. Sometimes, I cannot see nothing under Dev Tools of Chrome as the following screenshot shows, and I got the following error in the server.

![Screenshot 2020-04-07 at 08 37 56](https://user-images.githubusercontent.com/774409/78637874-8daeb800-78ab-11ea-8456-46bf2bb5ef31.png)


```
(base) Ties-MacBook-Pro:composer-language-server chengtie$ ./gradlew run

> Task :com.novomind.language.server.expression.websockets:run
start
open
message: {"jsonrpc":"2.0","method":"$/setTraceNotification","params":{"value":"off"}}
message: {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"rootPath":null,"rootUri":null,"capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true,"tagSupport":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true}}},"trace":"off","workspaceFolders":null}}
{"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":2,"hoverProvider":true,"completionProvider":{"resolveProvider":false,"triggerCharacters":["."]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":false,"documentFormattingProvider":true,"documentRangeFormattingProvider":true,"renameProvider":{"prepareProvider":true},"executeCommandProvider":{"commands":[]},"semanticHighlighting":{"scopes":[]}}}}
message: {"jsonrpc":"2.0","method":"initialized","params":{}}
message: {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"inmemory:/demo/b4af19e6-5c32-3552-733c-9cb0c893c2f2.expression","languageId":"expression","version":1,"text":"Hello Xtext!\nHello VSCode from Xtext!\nHello ThisFile from Other!\nHello you!"}}}
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"inmemory:/demo/b4af19e6-5c32-3552-733c-9cb0c893c2f2.expression","diagnostics":[{"range":{"start":{"line":2,"character":20},"end":{"line":2,"character":25}},"severity":1,"code":"org.eclipse.xtext.diagnostics.Diagnostic.Linking","message":"Couldn\u0027t resolve reference to Greeting \u0027Other\u0027."}]}}
```

Is it normal?

**Comment by nmaoez** [comment]
The network tab only shows requests which where sent while the network tab was opened. So if you don't see any requests then this doesn't automatically mean that no requests were sent. In your case I guess you have to reload the browser with the network tab open. For me everything works fine:
![grafik](https://user-images.githubusercontent.com/34936364/78644297-f13de300-78b5-11ea-8292-d6c885601904.png)

Also this is not an error in the console. Those are actually the messages which were sent between the server and the editor.

**Comment by chengtie** [comment]
Indeed, a good approach is to:

1. run `./gradlew run` in terminal
2. open a tab in Chrome and open Dev Tools
3. go `http://localhost:8080`

Then, we could see the communication of JSON under `Network` and `localhost`; and we see also the log in the terminal of the server.

Thank you.

Additionally, the reason I'm trying your composer-langauge-server is that I want to build a working example that connects Monaco Editor and ocaml-lsp: https://github.com/TypeFox/monaco-languageclient/issues/205. I will appreciate any comment and suggestion from your side.

**Comment by nmaoez** [comment]
Glad to see it's working for you now. I'll look into it if I have time.

Cheers.
